In [1]:
from deep_bf.webdataset.gsi.global_samples_idx_single_angle import GlobalSamplesIdxForTraining
from deep_bf.config_registery import ConfigRegisteryCenter, PathCenter

with ConfigRegisteryCenter() as cc:
    wdbC = cc.get_webdataset_beamformer_packing(id=3)

gsi = GlobalSamplesIdxForTraining(wdbC, location="local")

Computing samples_idx
Computing samples_idx done

In [2]:
from dataclasses import asdict
from deep_bf.config_registery import ConfigRegisteryCenter, PathCenter

with ConfigRegisteryCenter() as cc:
    print(cc.list_tables())

    print(asdict(cc.get_webdataset_beamformer_packing(id=0)))

with PathCenter() as pc:
    print(pc.dataset_paths.raw)

['activation', 'apod', 'architecture_cnn_bf', 'beamformer', 'conv2d_init', 'criterion', 'data_size', 'data_type', 'experiments', 'hyperparameters', 'model', 'optimizer', 'resampler', 'resize_gt', 'samples_organization', 'scheduler', 'schema_migrations', 'trainloop', 'transform_data', 'webdataset_beamformer']
{'webdataset_beamformer_config': {'id': 0, 'gt_source': 'DAS_mean', 'data_type_id': 0, 'data_size_id': 0, 'samples_organization_id': 1, 'transform_data_id': 0, 'resize_gt_id': 1}, 'data_type_config': {'id': 0, 'type': 'RF', 'params': {}}, 'data_size_config': {'id': 0, 'nz': 2048, 'nx': 256, 'ns': 2300}, 'samples_organization_config': {'id': 1, 'seed': 42, 'ratio': 0.9, 'order': 'CWH', 'select_mode': 'random_split', 'n_train': -1, 'n_val': -1, 'query': "(RF == 1) and (nc == 128) and (name.str.slice(0, 3) != 'JHU') and (source == 'CUBDL')", 'train_idxs': '-1', 'val_idxs': '-1'}, 'transform_data_config': {'id': 0, 'type': 'none', 'params': {}}, 'resize_gt_config': {'id': 1, 'type': 'resize', 'params': {'new_nz': 2048, 'new_nx': 256, 'mode': 'reflect'}}}
/home/panda/rf_data/dataset/raw

In [ ]:
from deep_bf.config_registery import ConfigRegisteryCenter, PathCenter
from deep_bf.webdataset.beamformer.create import beamformer_split_files

with ConfigRegisteryCenter() as cc:
    wdbC = cc.get_webdataset_beamformer_packing(id=2)

t, v = beamformer_split_files(wdbC, location="local")
print(len(t), len(v))

489 55

# Model

In [5]:
from deep_bf.config_registery import ConfigRegisteryCenter

tables = ["model", "architecture_cnn_bf", "conv2d_init", "activation", "beamformer"]
with ConfigRegisteryCenter() as cc:
    for table_name in tables:
        print(f"===== {table_name} =====")

        if table_name == "architecture_cnn_bf":
            df = cc.show_table("architecture_cnn_bf", limit=None, order_by="model_id")
        else:
            df = cc.show_table(table_name, limit=None, order_by="id")
        display(df)

===== model =====

    id   family  model_id  conv2d_init_id  activation_id  beamformer_id
0    0     BINN         1               0              0              0
1    1     BINN         2               0              0              0
2    2     BINN         3               0              0              0
3    3     BINN         4               0              0              0
4    4     BINN         5               0              0              0
5    5     BINN         6               0              0              0
6    6     BINN         7               0              0              0
7    7  BINN_OG         1               0              0              0
8    8  BINN_OG         2               0              0              0
9    9  BINN_OG         3               0              0              0
10  10  BINN_OG         4               0              0              0
11  11  BINN_OG         5               0              0              0
12  12  BINN_OG         6               0              0              0

===== architecture_cnn_bf =====

    model_id family  pos         type  ch_in  ch_out kernel_json padding  bias
0          1   BINN    0           BF      1       1    [-1, -1]    same     1
1          1   BINN    1  BasicConv2d      1      16      [5, 3]    same     1
2          1   BINN    2  BasicConv2d     16       8      [5, 3]    same     1
3          1   BINN    3  BasicConv2d      8       8      [5, 3]    same     1
4          1   BINN    4  BasicConv2d      8       4      [5, 3]    same     1
..       ...    ...  ...          ...    ...     ...         ...     ...   ...
80         7   BINN    2  BasicConv2d      8       8      [5, 3]    same     1
81         7   BINN    3  BasicConv2d      8       4      [5, 3]    same     1
82         7   BINN    4  BasicConv2d      4       2      [5, 3]    same     1
83         7   BINN    5  BasicConv2d      2       1      [7, 5]    same     1
84         7   BINN    6           BF      1       1    [-1, -1]    same     1

[85 rows x 9 columns]

===== conv2d_init =====

   id   init_weights init_bias
0   0  XavierUniform     Zeros

===== activation =====

   id       type               params_json
0   0  LeakyReLU  {"negative_slope": 0.01}

===== beamformer =====

   id type  resampler_id                                        params_json
0   0  DAS             1                                                 {}
1   1  MVB             1  {"z_chunk": 1024, "L": 16, "diagonal_loading":...

# Train Loop

In [ ]:
from deep_bf.config_registery import ConfigRegisteryCenter

tables = ["trainloop", "criterion", "optimizer", "scheduler", "hyperparameters"]
with ConfigRegisteryCenter() as cc:
    for table_name in tables:
        print(f"===== {table_name} =====")
        df = cc.show_table(table_name, limit=None, order_by="id")
        display(df)

===== trainloop =====

   id  criterion_id  optimizer_id  scheduler_id  hyperparameters_id
0   0             0             0             0                   0
1   1             0             0             0                   1

===== criterion =====

   id  type            params_json
0   0   MSE  {"reduction": "mean"}
1   1  MSLE  {"reduction": "mean"}

===== optimizer =====

   id  type                                        params_json
0   0  Adam  {"amsgrad": false, "betas": [0.9, 0.999], "eps...

===== scheduler =====

   id               type                                        params_json
0   0  ReduceLROnPlateau  {"factor": 0.5, "min_lr": 1e-06, "mode": "min"...

===== hyperparameters =====

   id  seed  n_epoch  batch_size  learning_rate
0   0    42      100           2          0.001
1   1    42      100           4          0.001

# Beamformer

In [ ]:
from deep_bf.config_registery import ConfigRegisteryCenter

tables = ["beamformer", "resampler", "apod"]
with ConfigRegisteryCenter() as cc:
    for table_name in tables:
        print(f"===== {table_name} =====")
        df = cc.show_table(table_name, limit=None, order_by="id")
        display(df)

===== beamformer =====

   id type  resampler_id                                        params_json
0   0  DAS             1                                                 {}
1   1  MVB             1  {"z_chunk": 1024, "L": 16, "diagonal_loading":...

===== resampler =====

   id                 type                                        params_json
0   0  LinearInterpolation                                                 {}
1   1           GridSample  {"align_corners": false, "mode": "bilinear", "...
2   2           GridSample  {"align_corners": false, "mode": "bilinear", "...
3   3           GridSample  {"align_corners": true, "mode": "bilinear", "p...
4   4           GridSample  {"align_corners": true, "mode": "bilinear", "p...

===== apod =====

   id                    type                           params_json
0   0                    None                                    {}
1   1  DynamicReceiveAperture      {"f_num": 1, "window": "boxcar"}
2   2  DynamicReceiveAperture  {"f_num": 1.75, "window": "hanning"}
3   3  DynamicReceiveAperture  {"f_num": 1.75, "window": "hamming"}
4   4  DynamicReceiveAperture  {"f_num": 1.75, "window": "tukey25"}

# Dataset

In [7]:
from deep_bf.config_registery import ConfigRegisteryCenter

tables = ["webdataset_beamformer", "data_size", "data_type", "samples_organization", "resize_gt", "transform_data"]
with ConfigRegisteryCenter() as cc:
    for table_name in tables:
        print(f"===== {table_name} =====")
        df = cc.show_table(table_name, limit=None, order_by="id")
        display(df)

===== webdataset_beamformer =====

,id,gt_source,data_type_id,data_size_id,samples_organization_id,transform_data_id,resize_gt_id
0,0,DAS,0,0,1,1,0
1,1,DAS,1,0,1,1,0
2,2,DAS,2,0,1,1,0
3,3,DAS,0,2,1,1,0
4,4,DAS,1,2,1,1,0
5,5,DAS,2,2,1,1,0

===== data_size =====

   id    nz   nx    ns
0   0  2048  256  2300
1   1  2048  256  2800
2   2  1024  256  2300

===== data_type =====

   id         type params_json
0   0           RF          {}
1   1  RF Analitic          {}
2   2           IQ          {}

===== samples_organization =====

,id,seed,ratio,order,select_mode,n_train,n_val,query,train_idxs,val_idxs
0,0,42,0.9,CWH,select_idxs,495,55,(RF == 1) and (nc == 128) and (name.str.slice(...,"0:12,14:19,22:51,53:57,59:70,72:86,89:90,92:98...","13,20:21,52,58,71,87:88,91,99,102,106,121,130,..."
1,1,42,0.9,CWH,random_split,-1,-1,(RF == 1) and (nc == 128) and (name.str.slice(...,-1,-1

===== resize_gt =====

   id      type                                        params_json
0   0  original                                                 {}
1   1    resize  {"new_nz": 2048, "new_nx":256, "mode": "reflect"}

===== transform_data =====

   id         type    params_json
0   0         none             {}
1   1  sharifzadeh  {"eps": 1e-8}

# Experiments

In [6]:
from deep_bf.config_registery import ConfigRegisteryCenter

tables = ["experiments"]
with ConfigRegisteryCenter() as cc:
    for table_name in tables:
        print(f"===== {table_name} =====")
        df = cc.show_table(table_name, limit=None, order_by="id")
        display(df)

===== experiments =====

,id,version,webdataset_beamformer_id,trainloop_id,model_id,commit_hash,commit_msg
0,0,1,5,0,7,unknown,
1,1,1,5,0,8,unknown,
2,2,1,5,0,9,unknown,
3,3,1,5,0,10,unknown,
4,4,1,5,0,11,unknown,
5,5,1,5,0,12,unknown,
6,6,1,2,0,7,unknown,
7,7,1,2,0,8,unknown,
8,8,1,2,0,9,unknown,
9,9,1,2,0,10,unknown,
10,10,1,2,0,11,unknown,
11,11,1,2,0,12,unknown,

# All

In [ ]:
from deep_bf.config_registery import ConfigRegisteryCenter

with ConfigRegisteryCenter() as cc:
    tables_list = cc.list_tables()
    for table_name in tables_list:
        if table_name == "schema_migrations":
            continue

        print(f"Table: {table_name}")
        if table_name == "architecture_cnn_bf":
            df = cc.show_table(table_name, limit=None, order_by="model_id")
        else:
            df = cc.show_table(table_name, limit=None, order_by="id")
        display(df)

    e = cc.get_experiment_packing(id=4)
    print(e)
    b = cc.get_beamformer_packing(id=1)
    print(b)
    a = cc.get_apod_config(id=4)
    print(a)
    m = cc.get_model_packing(id=1)
    print(m)
    w = cc.get_webdataset_packing(id=2)
    print(w)

Table: activation

   id       type               params_json
0   0  LeakyReLU  {"negative_slope": 0.01}

Table: apod

   id                    type                           params_json
0   0                    None                                    {}
1   1  DynamicReceiveAperture      {"f_num": 1, "window": "boxcar"}
2   2  DynamicReceiveAperture  {"f_num": 1.75, "window": "hanning"}
3   3  DynamicReceiveAperture  {"f_num": 1.75, "window": "hamming"}
4   4  DynamicReceiveAperture  {"f_num": 1.75, "window": "tukey25"}

Table: architecture_cnn_bf

,model_id,family,pos,type,ch_in,ch_out,kernel_json,padding,bias
0,3,BINN,0,BasicConv2d,1,16,"[5, 3]",same,1
1,3,BINN,1,BasicConv2d,16,8,"[5, 3]",same,1
2,3,BINN,2,BF,8,8,"[-1, -1]",same,1
3,3,BINN,3,BasicConv2d,8,8,"[5, 3]",same,1
4,3,BINN,4,BasicConv2d,8,4,"[5, 3]",same,1
5,3,BINN,5,BasicConv2d,4,2,"[5, 3]",same,1
6,3,BINN,6,BasicConv2d,2,1,"[7, 5]",same,1
7,3,BINN_OG,0,BasicConv2d,1,16,"[5, 3]",same,1
8,3,BINN_OG,1,BasicConv2d,16,8,"[5, 3]",same,1
9,3,BINN_OG,2,BF,8,8,"[-1, -1]",same,1
10,3,BINN_OG,3,BasicConv2d,8,8,"[5, 3]",same,1
11,3,BINN_OG,4,BasicConv2d,8,4,"[5, 3]",same,1
12,3,BINN_OG,5,BasicConv2d,4,1,"[7, 5]",same,1

Table: beamformer

   id type  resampler_id                                        params_json
0   0  DAS             1                                                 {}
1   1  MVB             1  {"z_chunk": 1024, "L": 16, "diagonal_loading":...

Table: conv2d_init

   id   init_weights init_bias
0   0  XavierUniform     Zeros

Table: criterion

   id type            params_json
0   0  MSE  {"reduction": "mean"}

Table: experiments

   id  version  webdataset_id  trainloop_id  model_id commit_hash commit_msg
0   0        1              0             0         0     unknown
1   1        1              1             0         0     unknown
2   2        1              2             0         0     unknown
3   3        1              3             0         0     unknown
4   4        1              2             0         1     unknown

Table: hyperparameters

   id  seed  n_epoch  batch_size  learning_rate
0   0    42      100           2          0.001
1   1    42      100           4          0.001

Table: model

   id   family  model_id  conv2d_init_id  activation_id  beamformer_id
0   0     BINN         3               0              0              0
1   1  BINN_OG         3               0              0              0

Table: optimizer

   id  type                                        params_json
0   0  Adam  {"amsgrad": false, "betas": [0.9, 0.999], "eps...

Table: resampler

   id                 type                                        params_json
0   0  LinearInterpolation                                                 {}
1   1           GridSample  {"align_corners": false, "mode": "bilinear", "...
2   2           GridSample  {"align_corners": false, "mode": "bilinear", "...
3   3           GridSample  {"align_corners": true, "mode": "bilinear", "p...
4   4           GridSample  {"align_corners": true, "mode": "bilinear", "p...

Table: resize_gt

   id      type                               params_json
0   0  original                                        {}
1   1    resize  {"nz_original": 2048, "mode": "reflect"}

Table: rf_transform

   id         type    params_json
0   0         none             {}
1   1  sharifzadeh  {"eps": 1e-8}

Table: scheduler

   id               type                                        params_json
0   0  ReduceLROnPlateau  {"factor": 0.5, "min_lr": 1e-06, "mode": "min"...

Table: trainloop

   id  criterion_id  optimizer_id  scheduler_id  hyperparameters_id
0   0             0             0             0                   0
1   1             0             0             0                   1

Table: webdataset

,id,seed,nz,nx,ns,ratio,order,n_train,n_val,select_mode,gt_source,rf_transform_id,resize_gt_id,query,train_idxs,val_idxs
0,0,42,2048,256,2800,0.9,CWH,495,55,select_idxs,DAS_mean,1,1,(RF == 1) and (nc == 128) and (name.str.slice(...,"0:12,14:19,22:51,53:57,59:70,72:86,89:90,92:98...","13,20:21,52,58,71,87:88,91,99,102,106,121,130,..."
1,1,42,2048,256,3072,0.9,CWH,-1,-1,random_split,DAS_mean,1,1,(RF == 1) and (nc == 128) and (name.str.slice(...,-1,-1
2,2,42,1024,256,3072,0.9,CWH,-1,-1,random_split,DAS_mean,1,1,(RF == 1) and (nc == 128) and (name.str.slice(...,-1,-1
3,3,42,512,256,3072,0.9,CWH,-1,-1,random_split,DAS_mean,1,1,(RF == 1) and (nc == 128) and (name.str.slice(...,-1,-1
4,4,42,256,256,3072,0.9,CWH,-1,-1,random_split,DAS_mean,1,1,(RF == 1) and (nc == 128) and (name.str.slice(...,-1,-1

ExperimentPacking(id=4, version=1, webdataset=WebDatasetPacking(webdataset_config=WebDatasetConfig(id=2, seed=42, nz=1024, nx=256, ns=3072, ratio=0.9, order='CWH', n_train=-1, n_val=-1, select_mode='random_split', gt_source='DAS_mean', rf_transform_id=1, resize_gt_id=1, query="(RF == 1) and (nc == 128) and (name.str.slice(0, 3) != 'JHU') and (source == 'CUBDL')", train_idxs='-1', val_idxs='-1'), rf_transform_config=RfTransformConfig(id=1, type='sharifzadeh', params={'eps': 1e-08}), resize_gt_config=ResizeGtConfig(id=1, type='resize', params={'nz_original': 2048, 'mode': 'reflect'})), trainloop=TrainLoopPacking(trainloop_config=TrainLoopConfig(id=0, criterion_id=0, optimizer_id=0, scheduler_id=0, hyperparameters_id=0), criterion_config=CriterionConfig(id=0, type='MSE', params={'reduction': 'mean'}), optimizer_config=OptimizerConfig(id=0, type='Adam', params={'amsgrad': False, 'betas': [0.9, 0.999], 'eps': 1e-07, 'weight_decay': 0.0}), scheduler_config=SchedulerConfig(id=0, type='ReduceLROnPlateau', params={'factor': 0.5, 'min_lr': 1e-06, 'mode': 'min', 'patience': 5, 'threshold': 0.0001}), hyperparameters_config=HyperparametersConfig(id=0, seed=42, n_epoch=100, batch_size=2, learning_rate=0.001)), model=ModelPacking(model_config=ModelConfig(id=1, family='BINN_OG', model_id=3, conv2d_init_id=0, activation_id=0, beamformer_id=0), conv2d_init_config=Conv2dInitConfig(id=0, init_weights='XavierUniform', init_bias='Zeros'), activation_config=ActivationConfig(id=0, type='LeakyReLU', params={'negative_slope': 0.01}), architecture_configs=[ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=0, type='BasicConv2d', ch_in=1, ch_out=16, kernel=(5, 3), padding='same', bias=True), ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=1, type='BasicConv2d', ch_in=16, ch_out=8, kernel=(5, 3), padding='same', bias=True), ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=2, type='BF', ch_in=8, ch_out=8, kernel=(-1, -1), padding='same', bias=True), ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=3, type='BasicConv2d', ch_in=8, ch_out=8, kernel=(5, 3), padding='same', bias=True), ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=4, type='BasicConv2d', ch_in=8, ch_out=4, kernel=(5, 3), padding='same', bias=True), ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=5, type='BasicConv2d', ch_in=4, ch_out=1, kernel=(7, 5), padding='same', bias=True)], beamformer=BeamformerPacking(beamformer_config=BeamformerConfig(id=0, type='DAS', resampler_id=1, params={}), resampler_config=ResamplerConfig(id=1, type='GridSample', params={'align_corners': False, 'mode': 'bilinear', 'padding_mode': 'zeros'}))), commit_hash='unknown', commit_msg='')
BeamformerPacking(beamformer_config=BeamformerConfig(id=1, type='MVB', resampler_id=1, params={'z_chunk': 1024, 'L': 16, 'diagonal_loading': 0.001, 'eps': 1e-10}), resampler_config=ResamplerConfig(id=1, type='GridSample', params={'align_corners': False, 'mode': 'bilinear', 'padding_mode': 'zeros'}))
ApodConfig(id=4, type='DynamicReceiveAperture', params={'f_num': 1.75, 'window': 'tukey25'})
ModelPacking(model_config=ModelConfig(id=1, family='BINN_OG', model_id=3, conv2d_init_id=0, activation_id=0, beamformer_id=0), conv2d_init_config=Conv2dInitConfig(id=0, init_weights='XavierUniform', init_bias='Zeros'), activation_config=ActivationConfig(id=0, type='LeakyReLU', params={'negative_slope': 0.01}), architecture_configs=[ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=0, type='BasicConv2d', ch_in=1, ch_out=16, kernel=(5, 3), padding='same', bias=True), ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=1, type='BasicConv2d', ch_in=16, ch_out=8, kernel=(5, 3), padding='same', bias=True), ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=2, type='BF', ch_in=8, ch_out=8, kernel=(-1, -1), padding='same', bias=True), ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=3, type='BasicConv2d', ch_in=8, ch_out=8, kernel=(5, 3), padding='same', bias=True), ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=4, type='BasicConv2d', ch_in=8, ch_out=4, kernel=(5, 3), padding='same', bias=True), ArchitectureCnnBfConfig(model_id=3, family='BINN_OG', pos=5, type='BasicConv2d', ch_in=4, ch_out=1, kernel=(7, 5), padding='same', bias=True)], beamformer=BeamformerPacking(beamformer_config=BeamformerConfig(id=0, type='DAS', resampler_id=1, params={}), resampler_config=ResamplerConfig(id=1, type='GridSample', params={'align_corners': False, 'mode': 'bilinear', 'padding_mode': 'zeros'})))
WebDatasetPacking(webdataset_config=WebDatasetConfig(id=2, seed=42, nz=1024, nx=256, ns=3072, ratio=0.9, order='CWH', n_train=-1, n_val=-1, select_mode='random_split', gt_source='DAS_mean', rf_transform_id=1, resize_gt_id=1, query="(RF == 1) and (nc == 128) and (name.str.slice(0, 3) != 'JHU') and (source == 'CUBDL')", train_idxs='-1', val_idxs='-1'), rf_transform_config=RfTransformConfig(id=1, type='sharifzadeh', params={'eps': 1e-08}), resize_gt_config=ResizeGtConfig(id=1, type='resize', params={'nz_original': 2048, 'mode': 'reflect'}))